local wk = require("which-key")

wk.register({
	f = {
		name = "Find",
		f = { "Find File" },
		b = { "Find Buffer" },
		h = { "Find Help" },
		w = { "Find by word" },
		p = { "Show persisted sessions" },
		s = { "Show file Symbols" },
	},
	e = { "Float file Manager" },
	E = { "Right side file Manager" },
	o = { "Git status" },
	x = { "Close active splitted screen" },
	X = { "Select tabs to close" },
	q = { "Close Buffer" },
	Q = { "Close NVIM" },
	w = { "Save" },
	h = { "No highlight" },
	g = {
		name = "Git",
		b = "Branches",
		c = "Commits",
		s = "Status",
		g = "Open Lazygit",
		l = "Toggle GitBlame",
	},
	l = {
		name = "LSP",
		d = "Diagnostic",
		D = "Hover diagnostic",
		f = "Format",
		r = "Rename",
		a = "Action",
		s = "Symbol",
	},
	r = {
		name = "Run",
		s = "Execute JS script with Bun",
	},
	t = {
		name = "Tests",
		t = "Run nearest test",
		S = "Stop running tests",
		s = "Show summary",
		a = "Run all nested tests",
		l = "Run last test",
		o = "Show error output",
		["["] = "Navigate to the prev test",
		["]"] = "Navigate to the next test",
	},
	m = {
		name = "Hop",
		a = "anywhere",
		C = "by 1 char",
		c = "by 1 or 2 chars",
		V = "to line at start",
		l = "to line at zero",
		v = "vertical",
		p = "by pattern",
		w = "to the word",
	},
	z = {
		name = "Zen mode",
		a = "Ataraxis mode",
		m = "Minimalist mode",
		n = "Narrow mode",
		f = "Focus mode",
	},
}, { prefix = "<leader>" })
