-- vim.cmd.colorscheme("kanagawa")
-- vim.cmd.colorscheme("ayu-mirage")
-- vim.cmd.colorscheme("dayfox")
-- vim.cmd.colorscheme("nightfox")
-- vim.cmd.colorscheme("darkplus")
vim.cmd.colorscheme("tokyonight-storm")
